name: Check Results

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:       # Manual run option

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run result checker script
        run: python satta_result_checker.py

      - name: Ensure required CSV files exist
        run: |
          touch satta_data.csv
          touch accuracy_log.csv
          touch sent_messages.csv
          echo "Ensured data files exist"

      - name: Commit updated CSV files if changed
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Bot"

          git add satta_data.csv || true
          git add accuracy_log.csv || true
          git add sent_messages.csv || true
          git add today_ml_prediction.csv || true

          git diff --cached --quiet || (
            git commit -m "Auto update CSV logs"
            git push
          )
